"""Adding table to track AWS Tags

Revision ID: 1974f1e5001e
Revises: 1727fb4309d8
Create Date: 2015-10-09 21:48:54.728830

"""

# revision identifiers, used by Alembic.
revision = '1974f1e5001e'
down_revision = '1727fb4309d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    op.create_index('ix_tag_value', 'tag', ['value'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_value', table_name='tag')
    op.drop_index('ix_tag_name', table_name='tag')
    op.drop_table('tag')
    ### end Alembic commands ###