"""custom role name

Revision ID: 51170afa2b48
Revises: 595e27f36454
Create Date: 2015-03-11 16:29:51.037379

"""

# revision identifiers, used by Alembic.
revision = '51170afa2b48'
down_revision = '595e27f36454'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('role_name', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'role_name')
    ### end Alembic commands ###
