"""Ability to link issues to other tech type items

Revision ID: ad23a56abf25
Revises: 67ea2aac5ea0
Create Date: 2016-02-23 18:52:45.024716

"""

# revision identifiers, used by Alembic.
revision = 'ad23a56abf25'
down_revision = '1a863bd1acb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_item_association',
    sa.Column('super_issue_id', sa.Integer(), nullable=True),
    sa.Column('sub_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['super_issue_id'], ['itemaudit.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_item_association')
    ### end Alembic commands ###
