"""empty message

Revision ID: bac85870ff4c
Revises: 1c847ae1209a
Create Date: 2017-02-09 16:46:03.437000

"""

# revision identifiers, used by Alembic.
revision = 'bac85870ff4c'
down_revision = '1c847ae1209a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobtype',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobtype_account_id', 'jobtype', ['account_id'], unique=False)
    op.create_index('ix_jobtype_status', 'jobtype', ['status'], unique=False)
    op.create_index('ix_jobtype_tech_id', 'jobtype', ['tech_id'], unique=False)
    op.create_table('jobschedulerun',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['job_type_id'], ['jobtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobschedulerun_date_completed', 'jobschedulerun', ['date_completed'], unique=False)
    op.create_index('ix_jobschedulerun_date_submitted', 'jobschedulerun', ['date_submitted'], unique=False)
    op.create_index('ix_jobschedulerun_job_id', 'jobschedulerun', ['job_id'], unique=False)
    op.create_index('ix_jobschedulerun_job_type_id', 'jobschedulerun', ['job_type_id'], unique=False)
    op.create_index('ix_jobschedulerun_status', 'jobschedulerun', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobschedulerun_status', table_name='jobschedulerun')
    op.drop_index('ix_jobschedulerun_job_type_id', table_name='jobschedulerun')
    op.drop_index('ix_jobschedulerun_job_id', table_name='jobschedulerun')
    op.drop_index('ix_jobschedulerun_date_submitted', table_name='jobschedulerun')
    op.drop_index('ix_jobschedulerun_date_completed', table_name='jobschedulerun')
    op.drop_table('jobschedulerun')
    op.drop_index('ix_jobtype_tech_id', table_name='jobtype')
    op.drop_index('ix_jobtype_status', table_name='jobtype')
    op.drop_index('ix_jobtype_account_id', table_name='jobtype')
    op.drop_table('jobtype')
    # ### end Alembic commands ###
