"""Distinguishes items created by different auditors of the same type

Revision ID: 0ae4ef82b244
Revises: ad23a56abf25
Create Date: 2016-03-25 19:07:11.312390

"""

# revision identifiers, used by Alembic.
revision = '0ae4ef82b244'
down_revision = '6245d75fa12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditorsettings', sa.Column('auditor_class', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auditorsettings', 'auditor_class')
    ### end Alembic commands ###
