"""Adding the ignorelist table.

Revision ID: 2705e6e13a8f
Revises: fb592c81e71
Create Date: 2014-11-01 19:02:35.149559

"""

# revision identifiers, used by Alembic.
revision = '2705e6e13a8f'
down_revision = 'fb592c81e71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignorelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tech_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ignorelist')
    ### end Alembic commands ###
