"""Increasing size of name field to accomodate longer AWS Resource IDs

Revision ID: 2ea41f4610fd
Revises: 1727fb4309d8
Create Date: 2016-04-18 17:59:04.622111

"""

# revision identifiers, used by Alembic.
revision = '2ea41f4610fd'
down_revision = '1727fb4309d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name', type_=sa.VARCHAR(303), existing_type=sa.VARCHAR(length=285), nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name', type_=sa.VARCHAR(285), existing_type=sa.VARCHAR(length=303), nullable=True)
    ### end Alembic commands ###
