"""Adding a fixed flag to the issue table

Revision ID: 4ac52090a637
Revises: daee17da2abd
Create Date: 2017-09-14 23:24:40.967949

"""

# revision identifiers, used by Alembic.
revision = '4ac52090a637'
down_revision = 'daee17da2abd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemaudit', sa.Column('fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemaudit', 'fixed')
    # ### end Alembic commands ###