"""Adding CloudTrail table and indexes everywhere!

Revision ID: e0a6af364a3f
Revises: bfb550a500ab
Create Date: 2016-07-27 17:49:23.243518

"""

# revision identifiers, used by Alembic.
revision = 'e0a6af364a3f'
down_revision = 'bfb550a500ab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudtrail',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=36), nullable=True),
        sa.Column('request_id', sa.String(length=36), nullable=True),
        sa.Column('event_source', sa.String(length=64), nullable=False),
        sa.Column('event_name', sa.String(length=64), nullable=False),
        sa.Column('event_time', sa.DateTime(), nullable=False),
        sa.Column('request_parameters', postgresql.JSON(), nullable=True),
        sa.Column('responseElements', postgresql.JSON(), nullable=True),
        sa.Column('source_ip', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=300), nullable=True),
        sa.Column('full_entry', postgresql.JSON(), nullable=True),
        sa.Column('user_identity', postgresql.JSON(), nullable=True),
        sa.Column('user_identity_arn', sa.String(length=300), nullable=True),
        sa.Column('revision_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
        sa.ForeignKeyConstraint(['revision_id'], ['itemrevision.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloudtrail_event_id', 'cloudtrail', ['event_id'], unique=True)
    op.create_index('ix_cloudtrail_event_time', 'cloudtrail', ['event_time'], unique=False)
    op.create_index('ix_cloudtrail_item_id', 'cloudtrail', ['item_id'], unique=False)
    op.create_index('ix_cloudtrail_request_id', 'cloudtrail', ['request_id'], unique=False)
    op.create_index('ix_cloudtrail_revision_id', 'cloudtrail', ['revision_id'], unique=False)
    op.create_index('ix_cloudtrail_user_identity_arn', 'cloudtrail', ['user_identity_arn'], unique=False)
    op.create_index('ix_auditorsettings_account_id', 'auditorsettings', ['account_id'], unique=False)
    op.create_index('ix_auditorsettings_tech_id', 'auditorsettings', ['tech_id'], unique=False)
    op.create_index('ix_ignorelist_tech_id', 'ignorelist', ['tech_id'], unique=False)
    op.create_index('ix_item_account_id', 'item', ['account_id'], unique=False)
    op.create_index('ix_item_tech_id', 'item', ['tech_id'], unique=False)

    op.create_index('ix_itemaudit_auditor_setting_id', 'itemaudit', ['auditor_setting_id'], unique=False)
    op.create_index('ix_itemaudit_item_id', 'itemaudit', ['item_id'], unique=False)
    op.create_index('ix_itemaudit_justified_user_id', 'itemaudit', ['justified_user_id'], unique=False)
    op.create_index('ix_itemcomment_item_id', 'itemcomment', ['item_id'], unique=False)
    op.create_index('ix_itemcomment_user_id', 'itemcomment', ['user_id'], unique=False)
    op.create_index('ix_itemrevision_item_id', 'itemrevision', ['item_id'], unique=False)
    op.create_index('ix_itemrevisioncomment_revision_id', 'itemrevisioncomment', ['revision_id'], unique=False)
    op.create_index('ix_itemrevisioncomment_user_id', 'itemrevisioncomment', ['user_id'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itemrevisioncomment_user_id', table_name='itemrevisioncomment')
    op.drop_index('ix_itemrevisioncomment_revision_id', table_name='itemrevisioncomment')
    op.drop_index('ix_itemrevision_item_id', table_name='itemrevision')
    op.drop_index('ix_itemcomment_user_id', table_name='itemcomment')
    op.drop_index('ix_itemcomment_item_id', table_name='itemcomment')
    op.drop_index('ix_itemaudit_justified_user_id', table_name='itemaudit')
    op.drop_index('ix_itemaudit_item_id', table_name='itemaudit')
    op.drop_index('ix_itemaudit_auditor_setting_id', table_name='itemaudit')
    op.drop_index('ix_item_tech_id', table_name='item')
    op.drop_index('ix_item_account_id', table_name='item')
    op.drop_index('ix_ignorelist_tech_id', table_name='ignorelist')
    op.drop_index('ix_auditorsettings_tech_id', table_name='auditorsettings')
    op.drop_index('ix_auditorsettings_account_id', table_name='auditorsettings')
    op.drop_index('ix_cloudtrail_user_identity_arn', table_name='cloudtrail')
    op.drop_index('ix_cloudtrail_revision_id', table_name='cloudtrail')
    op.drop_index('ix_cloudtrail_request_id', table_name='cloudtrail')
    op.drop_index('ix_cloudtrail_item_id', table_name='cloudtrail')
    op.drop_index('ix_cloudtrail_event_time', table_name='cloudtrail')
    op.drop_index('ix_cloudtrail_event_id', table_name='cloudtrail')
    op.drop_table('cloudtrail')
    ### end Alembic commands ###